// Generated by CoffeeScript 1.7.1
(function() {
  var $, FPS, draw, gameLoop, invert, update;

  $ = jQuery;

  $('#game').click(function(e) {});

  invert = true;

  $('#game').attr('tabindex', '0').keydown(function(e) {
    console.log(e.keyCode);
    if (e.keyCode === 87) {
      window.starField.setDirection("UP");
    }
    if (e.keyCode === 83) {
      window.starField.setDirection("DOWN");
    }
    if (e.keyCode === 65) {
      window.starField.setDirection("LEFT");
    }
    if (e.keyCode === 68) {
      window.starField.setDirection("RIGHT");
    }
    if (e.keyCode === 81) {
      window.starField.freeze();
    }
    if (e.keyCode === 69) {
      window.starField.resume();
    }
    if (e.keyCode === 73) {
      if (invert) {
        window.starField.setColor('#000000');
        window.starField.setBg('#ffffff');
        invert = false;
      } else {
        window.starField.setColor('#ffffff');
        window.starField.setBg('#000000');
        invert = true;
      }
    }
    if (e.keyCode === 74) {
      window.starField.changeSpeed(-1);
    }
    if (e.keyCode === 75) {
      return window.starField.changeSpeed(1);
    }
  });

  $('#gamebox').mousemove(function(e) {});

  FPS = 100;

  window.canvas = document.getElementById('game');

  window.rect = window.canvas.getBoundingClientRect();

  window.canvas.width = window.canvas.height = 570;

  window.ctx = window.canvas.getContext('2d');

  window.starField = StarField.getInstance("CIRCLE", 1, 1, "UP", "#ffffff", 100, 4);

  update = function() {
    window.starField.moveStars();
  };

  draw = function() {
    window.ctx.clearRect(0, 0, window.canvas.width, window.canvas.height);
    window.starField.draw();
  };

  gameLoop = function() {
    update();
    draw();
  };

  setInterval(gameLoop, 1000 / FPS);

}).call(this);
